import type { GraphEdge } from "./types";

export const graphEdges: GraphEdge[] = [
  {
    id: "edge-truth-justice",
    source: "idea-truth",
    target: "idea-justice",
    relation: "fundamenta",
    label: "Sem verdade factual, não há julgamento justo.",
    evidenceStatus: "pedagogica",
    strength: 5,
  },
  {
    id: "edge-goodness-justice",
    source: "idea-goodness",
    target: "idea-justice",
    relation: "fundamenta",
    label: "A justiça depende de uma ideia do bem humano.",
    evidenceStatus: "pedagogica",
    strength: 5,
  },
  {
    id: "edge-justice-liberty",
    source: "idea-justice",
    target: "idea-liberty",
    relation: "limita",
    label: "Justiça limita a liberdade quando ela vira licença.",
    evidenceStatus: "pedagogica",
    strength: 5,
  },
  {
    id: "edge-justice-equality",
    source: "idea-justice",
    target: "idea-equality",
    relation: "corrige",
    label: "Justiça distingue igualdade de dignidade de nivelamento injusto.",
    evidenceStatus: "pedagogica",
    strength: 5,
  },
  {
    id: "edge-beauty-truth",
    source: "idea-beauty",
    target: "idea-truth",
    relation: "tensiona",
    label: "A beleza pode revelar ordem verdadeira, mas também pode iludir.",
    evidenceStatus: "pedagogica",
    strength: 4,
  },
  {
    id: "edge-beauty-goodness",
    source: "idea-beauty",
    target: "idea-goodness",
    relation: "expande",
    label: "A beleza pode ser compreendida como uma forma de bem contemplativo.",
    evidenceStatus: "pedagogica",
    strength: 4,
  },
  {
    id: "edge-liberty-equality",
    source: "idea-liberty",
    target: "idea-equality",
    relation: "tensiona",
    label: "A liberdade pode gerar desigualdades; a igualdade pode restringir liberdades.",
    evidenceStatus: "pedagogica",
    strength: 5,
  },
  // Arestas de ideias associadas compartilhadas
  {
    id: "edge-prazer-beauty",
    source: "assoc-prazer",
    target: "idea-beauty",
    relation: "aplica_se_a",
    label: "O prazer estético é um modo específico de prazer ligado à contemplação.",
    evidenceStatus: "inferida",
    strength: 3,
  },
  {
    id: "edge-lei-justice",
    source: "assoc-lei",
    target: "idea-justice",
    relation: "aplica_se_a",
    label: "A lei é o instrumento pelo qual a justiça se torna efetiva na sociedade.",
    evidenceStatus: "pedagogica",
    strength: 4,
  },
  {
    id: "edge-dever-justice",
    source: "assoc-dever",
    target: "idea-justice",
    relation: "fundamenta",
    label: "O dever moral é o fundamento da justiça nas teorias deontológicas.",
    evidenceStatus: "inferida",
    strength: 4,
  },
  {
    id: "edge-bem-comum-justice",
    source: "assoc-bem-comum",
    target: "idea-justice",
    relation: "fundamenta",
    label: "O bem comum é o critério pelo qual a justiça social é avaliada.",
    evidenceStatus: "pedagogica",
    strength: 4,
  },
  {
    id: "edge-direitos-equality",
    source: "assoc-direitos",
    target: "idea-equality",
    relation: "fundamenta",
    label: "Direitos iguais são a expressão jurídica da igualdade de dignidade.",
    evidenceStatus: "pedagogica",
    strength: 4,
  },
];
