import type { GraphNode } from "./types";

// ── Seis Grandes Ideias ─────────────────────────────────────────────────────

export const greatIdeaNodes: GraphNode[] = [
  {
    id: "idea-truth",
    label: "Verdade",
    type: "great_idea",
    slug: "verdade",
    axis: "como_julgamos",
    question: "O que penso corresponde ao real?",
    summary:
      "Verdade é a ideia que mede a relação entre pensamento, linguagem e realidade.",
  },
  {
    id: "idea-goodness",
    label: "Bondade",
    type: "great_idea",
    slug: "bem",
    axis: "como_julgamos",
    question: "O que desejo é realmente bom para uma vida humana?",
    summary:
      "Bondade é a ideia que distingue bens reais de bens aparentes, necessidades de desejos e fins humanos de preferências subjetivas.",
  },
  {
    id: "idea-beauty",
    label: "Beleza",
    type: "great_idea",
    slug: "beleza",
    axis: "como_julgamos",
    question: "O belo está no objeto, no sujeito ou no encontro entre forma e contemplação?",
    summary:
      "Beleza é a ideia que julga aquilo que é digno de contemplação, prazer estético e admiração.",
  },
  {
    id: "idea-liberty",
    label: "Liberdade",
    type: "great_idea",
    slug: "liberdade",
    axis: "como_agimos",
    question: "Até onde posso fazer o que quero sem ferir o outro?",
    summary:
      "Liberdade é a capacidade de escolher, agir e participar da vida comum sem coerção injusta, mas também sem cair na licença.",
  },
  {
    id: "idea-equality",
    label: "Igualdade",
    type: "great_idea",
    slug: "igualdade",
    axis: "como_agimos",
    question: "Em que sentido todos os seres humanos são iguais?",
    summary:
      "Igualdade é a ideia que pergunta em que sentido todos devem ser tratados como iguais e em que sentido diferenças reais podem justificar tratamentos diferentes.",
  },
  {
    id: "idea-justice",
    label: "Justiça",
    type: "great_idea",
    slug: "justica",
    axis: "como_agimos",
    question: "O que devemos uns aos outros?",
    summary:
      "Justiça é a ideia que julga ações, leis, governos, punições, direitos, deveres e distribuições.",
  },
];

// ── Ideias Associadas ───────────────────────────────────────────────────────

type AssociatedIdeaInput = Omit<GraphNode, "type"> & { greatIdeaId: string };

const associatedIdeasRaw: AssociatedIdeaInput[] = [
  // ── Verdade (10) ──
  {
    id: "assoc-conhecimento",
    label: "Conhecimento",
    slug: "conhecimento",
    summary: "A capacidade de apreender a realidade com certeza e justificativa.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-opiniao",
    label: "Opinião",
    slug: "opiniao",
    summary: "Crença sem certeza plena — distinta do conhecimento científico.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-erro",
    label: "Erro",
    slug: "erro",
    summary: "Afirmação que não corresponde à realidade.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-mentira",
    label: "Mentira",
    slug: "mentira",
    summary: "Afirmação falsa proferida com intenção de enganar.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-realidade",
    label: "Realidade",
    slug: "realidade",
    summary: "O conjunto do que existe independente de nossa percepção.",
    axis: "transversal",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-linguagem",
    label: "Linguagem",
    slug: "linguagem",
    summary: "Sistema simbólico pelo qual expressamos e transmitimos pensamentos.",
    axis: "transversal",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-ciencia",
    label: "Ciência",
    slug: "ciencia",
    summary: "Conhecimento metódico e verificável da realidade.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-logica",
    label: "Lógica",
    slug: "logica",
    summary: "Ciência das formas válidas de raciocínio.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-evidencia",
    label: "Evidência",
    slug: "evidencia",
    summary: "Dados ou razões que sustentam ou refutam uma afirmação.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },
  {
    id: "assoc-ceticismo",
    label: "Ceticismo",
    slug: "ceticismo",
    summary: "Postura filosófica que questiona a possibilidade do conhecimento certo.",
    axis: "como_julgamos",
    greatIdeaId: "idea-truth",
  },

  // ── Bondade (10) ──
  {
    id: "assoc-desejo",
    label: "Desejo",
    slug: "desejo",
    summary: "Tendência da vontade em direção a um bem percebido.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-necessidade",
    label: "Necessidade",
    slug: "necessidade",
    summary: "O que é indispensável para o florescimento humano.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-felicidade",
    label: "Felicidade",
    slug: "felicidade",
    summary: "Estado de realização ou beatitude associado ao bem supremo.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-virtude",
    label: "Virtude",
    slug: "virtude",
    summary: "Excelência moral que dispõe o ser humano ao bem.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-prazer",
    label: "Prazer",
    slug: "prazer",
    summary:
      "Satisfação sensível ou intelectual, distinguida do bem real pela tradição aristotélica.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-dever",
    label: "Dever",
    slug: "dever",
    summary: "Obrigação moral que orienta a ação independente das consequências.",
    axis: "como_agimos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-fim",
    label: "Fim",
    slug: "fim",
    summary: "Propósito ou telos para o qual a ação humana está orientada.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-bem-comum",
    label: "Bem Comum",
    slug: "bem-comum",
    summary: "O bem que pertence à comunidade e não apenas ao indivíduo.",
    axis: "como_agimos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-mal",
    label: "Mal",
    slug: "mal",
    summary: "Privação do bem ou oposição ao florescimento humano.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },
  {
    id: "assoc-vicio",
    label: "Vício",
    slug: "vicio",
    summary: "Hábito que deforma a vontade e afasta do bem.",
    axis: "como_julgamos",
    greatIdeaId: "idea-goodness",
  },

  // ── Beleza (10) ──
  {
    id: "assoc-arte",
    label: "Arte",
    slug: "arte",
    summary: "Produção humana orientada pela busca do belo e da expressão.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-forma",
    label: "Forma",
    slug: "forma",
    summary: "Estrutura ou proporção que confere beleza e inteligibilidade ao ser.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-prazer-estetico",
    label: "Prazer Estético",
    slug: "prazer-estetico",
    summary: "Fruição sensível ou contemplativa de algo considerado belo.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-gosto",
    label: "Gosto",
    slug: "gosto",
    summary: "Capacidade de julgar o belo, discutida entre objetivistas e subjetivistas.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-proporcao",
    label: "Proporção",
    slug: "proporcao",
    summary: "Relação harmônica entre as partes que produz beleza.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-contemplacao",
    label: "Contemplação",
    slug: "contemplacao",
    summary: "Ato de apreciar algo desinteressadamente pelo que ele é.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-natureza",
    label: "Natureza",
    slug: "natureza",
    summary: "O mundo físico como fonte de beleza e ordem.",
    axis: "transversal",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-poesia",
    label: "Poesia",
    slug: "poesia",
    summary: "Forma de linguagem que imita e revela a beleza do real.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-sublime",
    label: "Sublime",
    slug: "sublime",
    summary: "Experiência de grandiosidade que ultrapassa o belo e provoca assombro.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },
  {
    id: "assoc-harmonia",
    label: "Harmonia",
    slug: "harmonia",
    summary: "Consonância entre partes que produz prazer estético.",
    axis: "como_julgamos",
    greatIdeaId: "idea-beauty",
  },

  // ── Liberdade (10) ──
  {
    id: "assoc-vontade",
    label: "Vontade",
    slug: "vontade",
    summary: "Faculdade pela qual o ser humano delibera e escolhe.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-lei",
    label: "Lei",
    slug: "lei",
    summary: "Norma racional ou positiva que regula a vida em comum.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-coercao",
    label: "Coerção",
    slug: "coercao",
    summary: "Força que constrange a vontade do outro contra sua razão.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-livre-arbitrio",
    label: "Livre-Arbítrio",
    slug: "livre-arbitrio",
    summary:
      "Capacidade de agir sem determinação necessária — questão central na teologia e na filosofia.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-autonomia",
    label: "Autonomia",
    slug: "autonomia",
    summary: "Capacidade de dar-se a si mesmo a lei racional.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-tirania",
    label: "Tirania",
    slug: "tirania",
    summary: "Poder sem lei que nega a liberdade dos governados.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-cidadania",
    label: "Cidadania",
    slug: "cidadania",
    summary: "Participação ativa na vida política da comunidade.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-direitos",
    label: "Direitos",
    slug: "direitos",
    summary: "Prerrogativas que cada pessoa possui por ser humana ou cidadã.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-responsabilidade",
    label: "Responsabilidade",
    slug: "responsabilidade",
    summary: "Condição de ser autor de ações e responder por elas.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },
  {
    id: "assoc-licenca",
    label: "Licença",
    slug: "licenca",
    summary: "Liberdade sem freio — uso da liberdade para prejudicar outros.",
    axis: "como_agimos",
    greatIdeaId: "idea-liberty",
  },

  // ── Igualdade (10) ──
  {
    id: "assoc-dignidade",
    label: "Dignidade",
    slug: "dignidade",
    summary: "Valor intrínseco que pertence a todo ser humano.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-merito",
    label: "Mérito",
    slug: "merito",
    summary: "Desigualdade justificável baseada em esforço ou capacidade.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-oportunidade",
    label: "Oportunidade",
    slug: "oportunidade",
    summary: "Condições mínimas para que cada um possa desenvolver suas capacidades.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-condicao",
    label: "Condição",
    slug: "condicao",
    summary: "Circunstâncias materiais e sociais que moldam a vida de cada pessoa.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-direitos-politicos",
    label: "Direitos dos Cidadãos",
    slug: "direitos-politicos",
    summary: "Prerrogativas iguais garantidas a todos os membros de uma comunidade política.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-democracia",
    label: "Democracia",
    slug: "democracia",
    summary: "Forma de governo fundada na igualdade política dos cidadãos.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-distribuicao",
    label: "Distribuição",
    slug: "distribuicao",
    summary: "Alocação de bens, encargos e direitos numa sociedade.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-proporcao-politica",
    label: "Proporção Política",
    slug: "proporcao-politica",
    summary:
      "Princípio aristotélico de que a igualdade justa trata iguais igualmente e desiguais desigualmente.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-diferenca",
    label: "Diferença",
    slug: "diferenca",
    summary: "Reconhecimento de que desigualdades reais existem e podem ou não ser justas.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },
  {
    id: "assoc-justica-social",
    label: "Justiça Social",
    slug: "justica-social",
    summary: "Distribuição equânime dos benefícios e encargos da cooperação social.",
    axis: "como_agimos",
    greatIdeaId: "idea-equality",
  },

  // ── Justiça (10) ──
  {
    id: "assoc-lei-positiva",
    label: "Lei Positiva",
    slug: "lei-positiva",
    summary: "Norma estabelecida por autoridade humana para regular a convivência.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-direito",
    label: "Direito",
    slug: "direito",
    summary: "Sistema de normas que regulam relações entre pessoas e o Estado.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-dever-moral",
    label: "Dever Moral",
    slug: "dever-moral",
    summary: "Obrigação ética que transcende a lei positiva e funda a justiça.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-estado",
    label: "Estado",
    slug: "estado",
    summary: "Instituição política que detém o monopólio legítimo da força.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-punicao",
    label: "Punição",
    slug: "punicao",
    summary: "Resposta punitiva da sociedade a uma violação da lei.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-equidade",
    label: "Equidade",
    slug: "equidade",
    summary: "Adaptação da lei geral ao caso particular para evitar injustiças.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-contrato-social",
    label: "Contrato Social",
    slug: "contrato-social-conceito",
    summary: "Acordo mútuo que funda obrigações e legitima o poder político.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-bem-coletivo",
    label: "Bem Coletivo",
    slug: "bem-coletivo",
    summary: "O bem que pertence à comunidade como um todo e orienta a lei justa.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-autoridade",
    label: "Autoridade",
    slug: "autoridade",
    summary: "Poder reconhecido como legítimo pelos que a ele obedecem.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
  {
    id: "assoc-ordem",
    label: "Ordem",
    slug: "ordem",
    summary: "Arranjo estável das relações sociais que torna a vida em comum possível.",
    axis: "como_agimos",
    greatIdeaId: "idea-justice",
  },
];

export const associatedIdeaNodes: GraphNode[] = associatedIdeasRaw.map(
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  ({ greatIdeaId: _greatIdeaId, ...rest }) => ({
    ...rest,
    type: "associated_idea" as const,
  }),
);

export const allNodes: GraphNode[] = [...greatIdeaNodes, ...associatedIdeaNodes];

// Map: greatIdeaId → list of associatedIdea ids
export const associatedIdeasByGreatIdea: Record<string, string[]> =
  associatedIdeasRaw.reduce<Record<string, string[]>>((acc, { id, greatIdeaId }) => {
    if (!acc[greatIdeaId]) acc[greatIdeaId] = [];
    acc[greatIdeaId].push(id);
    return acc;
  }, {});
