import type { GBWWVolume } from "./types";

const GB_BASE =
  "C:\\Users\\Usuario\\Downloads\\Syntopicon+102ideias\\54-volumes-great-books\\Encyclopædia Britannica - Great Books of the Western World, Volume";

export const gbwwVolumes: GBWWVolume[] = [
  {
    id: "gbww-02",
    volumeNumber: 2,
    title: "Volume 2 — The Great Ideas I",
    shortTitle: "The Great Ideas I",
    authors: ["Mortimer J. Adler", "Robert Maynard Hutchins"],
    works: ["Syntopicon I"],
    period: "Século XX",
    category: "introductory",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 2 - The Great Ideas I.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/2",
    description:
      "Volume introdutório que contém o Syntopicon — o índice filosófico das 102 grandes ideias do pensamento ocidental. O capítulo Justice (capítulo 42) está aqui.",
    connectedIdeaIds: ["justica", "liberdade", "igualdade", "verdade", "bem"],
    connectedTopicIds: [
      "justice-force-vs-right",
      "justice-distributive-corrective",
      "justice-natural-law-positive-law",
    ],
  },
  {
    id: "gbww-05",
    volumeNumber: 5,
    title: "Volume 5 — Aeschylus, Sophocles, Euripides, Aristophanes",
    shortTitle: "Tragédia Grega",
    authors: ["Ésquilo", "Sófocles", "Eurípides", "Aristófanes"],
    works: ["Oresteia", "Eumênides", "Antígona", "Édipo Rei"],
    period: "Século V a.C.",
    category: "classical_antiquity",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 5 - Aeschylus, Sophocles, Euripides, Aristophanes.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/5",
    description:
      "A tragédia grega inaugura o debate filosófico sobre justiça. A Oresteia de Ésquilo dramatiza a transição da vingança privada para o julgamento público. Antígona confronta lei divina e lei da cidade.",
    connectedIdeaIds: ["justica", "lei", "punição"],
    connectedTopicIds: [
      "justice-vengeance-vs-civic-judgment",
      "justice-unwritten-law-vs-state-law",
      "justice-punishment",
    ],
  },
  {
    id: "gbww-06",
    volumeNumber: 6,
    title: "Volume 6 — Herodotus, Thucydides",
    shortTitle: "Heródoto e Tucídides",
    authors: ["Heródoto", "Tucídides"],
    works: ["Histórias", "História da Guerra do Peloponeso"],
    period: "Século V a.C.",
    category: "classical_antiquity",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 6 - Herodotus, Thucydides.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/6",
    description:
      "Tucídides registra o Diálogo dos Mélios — o argumento mais brutal de que o forte faz o que pode e o fraco sofre o que deve. Referência central ao tópico Força vs. Direito.",
    connectedIdeaIds: ["justica", "poder", "guerra"],
    connectedTopicIds: ["justice-force-vs-right"],
  },
  {
    id: "gbww-07",
    volumeNumber: 7,
    title: "Volume 7 — Plato",
    shortTitle: "Platão",
    authors: ["Platão"],
    works: ["A República", "Górgias", "Leis", "Críton", "Fédon"],
    period: "Século IV a.C.",
    category: "classical_antiquity",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 7 - Plato.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/7",
    description:
      "Platão transforma a questão da justiça em investigação filosófica sistemática. Em A República, enfrenta a tese de Trasímaco de que justiça é a vantagem do mais forte. Propõe que a justiça é harmonia — na alma e na cidade.",
    connectedIdeaIds: ["justica", "verdade", "bondade", "beleza", "liberdade"],
    connectedTopicIds: [
      "justice-force-vs-right",
      "justice-soul-and-city",
      "justice-natural-law-positive-law",
    ],
  },
  {
    id: "gbww-09",
    volumeNumber: 9,
    title: "Volume 9 — Aristotle II",
    shortTitle: "Aristóteles II",
    authors: ["Aristóteles"],
    works: ["Ética a Nicômaco", "Política"],
    period: "Século IV a.C.",
    category: "classical_antiquity",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 9 - Aristotle II.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/9",
    description:
      "Aristóteles formula a teoria mais influente da justiça na tradição ocidental. Distingue justiça distributiva (proporção geométrica) e corretiva (proporção aritmética). A justiça política depende de uma constituição que distribua cargos e bens.",
    connectedIdeaIds: ["justica", "igualdade", "virtude", "lei"],
    connectedTopicIds: [
      "justice-distributive-corrective",
      "justice-soul-and-city",
      "justice-natural-law-positive-law",
    ],
  },
  {
    id: "gbww-18",
    volumeNumber: 18,
    title: "Volume 18 — Augustine",
    shortTitle: "Agostinho",
    authors: ["Agostinho de Hipona"],
    works: ["Cidade de Deus", "Confissões"],
    period: "Séculos IV–V d.C.",
    category: "middle_ages_renaissance",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 18 - Augustine.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/18",
    description:
      "Agostinho pergunta: pode haver justiça verdadeira sem Deus? Reinos sem justiça não passam de grandes bandos de ladrões. A justiça divina transcende e julga toda justiça humana.",
    connectedIdeaIds: ["justica", "deus", "lei", "estado"],
    connectedTopicIds: [
      "justice-natural-law-positive-law",
      "justice-contract-sovereignty",
    ],
  },
  {
    id: "gbww-19",
    volumeNumber: 19,
    title: "Volume 19 — Thomas Aquinas I",
    shortTitle: "Tomás de Aquino I",
    authors: ["Tomás de Aquino"],
    works: ["Suma Teológica (Parte I e I-II)"],
    period: "Século XIII",
    category: "middle_ages_renaissance",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 19 - Thomas Aquinas I.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/19",
    description:
      "Tomás de Aquino articula a doutrina da lei natural: a lei humana deriva da razão e deve conformar-se à lei eterna de Deus. A justiça é dar a cada um o que lhe é devido, orientada pelo bem comum.",
    connectedIdeaIds: ["justica", "lei", "dever", "bem"],
    connectedTopicIds: [
      "justice-natural-law-positive-law",
      "justice-distributive-corrective",
    ],
  },
  {
    id: "gbww-20",
    volumeNumber: 20,
    title: "Volume 20 — Thomas Aquinas II",
    shortTitle: "Tomás de Aquino II",
    authors: ["Tomás de Aquino"],
    works: ["Suma Teológica (Parte II-II e III)"],
    period: "Século XIII",
    category: "middle_ages_renaissance",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 20 - Thomas Aquinas II.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/20",
    description:
      "A segunda parte da Suma Teológica aprofunda as virtudes morais, incluindo a justiça como virtude cardeal. Detalha justiça comutativa, distributiva e legal, e examina os vícios opostos.",
    connectedIdeaIds: ["justica", "virtude", "lei", "dever"],
    connectedTopicIds: [
      "justice-distributive-corrective",
      "justice-natural-law-positive-law",
    ],
  },
  {
    id: "gbww-23",
    volumeNumber: 23,
    title: "Volume 23 — Machiavelli, Hobbes",
    shortTitle: "Maquiavel e Hobbes",
    authors: ["Nicolau Maquiavel", "Thomas Hobbes"],
    works: ["O Príncipe", "Leviatã"],
    period: "Séculos XVI–XVII",
    category: "early_modern",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 23 - Machiavelli, Hobbes.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/23",
    description:
      "Hobbes faz a justiça depender do poder civil: no estado de natureza, não há injustiça porque não há lei. O contrato social cria soberano e, com ele, a possibilidade de justiça e injustiça.",
    connectedIdeaIds: ["justica", "lei", "estado", "liberdade"],
    connectedTopicIds: [
      "justice-contract-sovereignty",
      "justice-force-vs-right",
      "justice-natural-law-positive-law",
    ],
  },
  {
    id: "gbww-35",
    volumeNumber: 35,
    title: "Volume 35 — Locke, Berkeley, Hume",
    shortTitle: "Locke, Berkeley, Hume",
    authors: ["John Locke", "George Berkeley", "David Hume"],
    works: [
      "Segundo Tratado sobre o Governo Civil",
      "Tratado da Natureza Humana",
      "Investigação sobre os Princípios da Moral",
    ],
    period: "Séculos XVII–XVIII",
    category: "early_modern",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 35 - Locke, Berkeley, Hume.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/35",
    description:
      "Locke fundamenta a justiça em direitos naturais à vida, liberdade e propriedade. Hume a transforma em virtude artificial — útil, convencional, dependente do acordo social, não de uma lei natural independente.",
    connectedIdeaIds: ["justica", "liberdade", "propriedade", "lei"],
    connectedTopicIds: [
      "justice-natural-law-positive-law",
      "justice-utility-convention",
      "justice-contract-sovereignty",
    ],
  },
  {
    id: "gbww-42",
    volumeNumber: 42,
    title: "Volume 42 — Kant",
    shortTitle: "Kant",
    authors: ["Immanuel Kant"],
    works: [
      "Crítica da Razão Pura",
      "Metafísica dos Costumes",
      "Fundamentação da Metafísica dos Costumes",
    ],
    period: "Século XVIII",
    category: "early_modern",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 42 - Kant.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/42",
    description:
      "Kant define a justiça como a coexistência das liberdades externas de todos sob uma lei universal. A Ciência do Direito (Rechtslehre) formula: age de modo que o uso de tua liberdade possa coexistir com a liberdade de todos segundo uma lei universal.",
    connectedIdeaIds: ["justica", "liberdade", "dever", "lei"],
    connectedTopicIds: [
      "justice-liberty-universal-law",
      "justice-natural-law-positive-law",
    ],
  },
  {
    id: "gbww-43",
    volumeNumber: 43,
    title: "Volume 43 — American State Papers, The Federalist, J. S. Mill",
    shortTitle: "Federalist & Mill",
    authors: [
      "Alexander Hamilton",
      "James Madison",
      "John Jay",
      "John Stuart Mill",
    ],
    works: [
      "The Federalist Papers",
      "Sobre a Liberdade",
      "Utilitarismo",
      "Considerações sobre o Governo Representativo",
    ],
    period: "Séculos XVIII–XIX",
    category: "nineteenth_century",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 43 - American State Papers, The Federalist, J S Mill.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/43",
    description:
      "Mill formula o princípio da utilidade como critério de justiça: maximizar a felicidade geral. Os Federalist Papers articulam como a constituição protege os direitos individuais frente à tirania da maioria.",
    connectedIdeaIds: ["justica", "liberdade", "democracia", "lei"],
    connectedTopicIds: [
      "justice-utility-convention",
      "justice-liberty-universal-law",
      "justice-distributive-corrective",
    ],
  },
  {
    id: "gbww-50",
    volumeNumber: 50,
    title: "Volume 50 — Marx, Engels",
    shortTitle: "Marx e Engels",
    authors: ["Karl Marx", "Friedrich Engels"],
    works: ["O Capital", "Manifesto Comunista", "A Ideologia Alemã"],
    period: "Século XIX",
    category: "nineteenth_century",
    archivePdfUrl: "",
    localFilePath: `${GB_BASE} 50 - Marx, Engels.pdf`,
    externalPdfUrl: "",
    internalPageUrl: "/volumes/50",
    description:
      "Marx critica a justiça burguesa como ideologia que legitima a exploração do trabalho. A verdadeira justiça exigiria a abolição das classes. 'De cada um segundo sua capacidade, a cada um segundo sua necessidade.'",
    connectedIdeaIds: ["justica", "trabalho", "propriedade", "igualdade"],
    connectedTopicIds: ["justice-economic-class", "justice-distributive-corrective"],
  },
];

export function getVolumeByNumber(n: number): GBWWVolume | undefined {
  return gbwwVolumes.find((v) => v.volumeNumber === n);
}

export function getVolumesByIdea(ideaSlug: string): GBWWVolume[] {
  return gbwwVolumes.filter((v) => v.connectedIdeaIds.includes(ideaSlug));
}

export function getJusticeVolumes(): GBWWVolume[] {
  return getVolumesByIdea("justica");
}
