import type { SyntopiconReference } from "./types";

export const syntopiconReferences: SyntopiconReference[] = [
  // ── FORÇA VS. DIREITO ──────────────────────────────────────────────────────
  {
    id: "ref-justice-plato-republic-thrasymachus",
    ideaSlug: "justica",
    topicId: "justice-force-vs-right",
    debateId: "force-vs-right",
    displayReference: "Platão — A República, Livro I",
    technicalReference: "GBWW Vol. 7 · Plato · Republic · BK I · localização em verificação",
    gbwwVolume: 7,
    volumeTitle: "Volume 7 — Plato",
    volumePageUrl: "/volumes/7",
    volumePdfUrl: "",
    author: "Platão",
    work: "A República",
    internalLocation: "Livro I",
    role: "Apresenta a tese de Trasímaco: justiça é a vantagem do mais forte. Sócrates a refuta mostrando que todo governante, enquanto governante, governa em benefício do governado.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "verdade", "liberdade"],
  },
  {
    id: "ref-justice-thucydides-melian-dialogue",
    ideaSlug: "justica",
    topicId: "justice-force-vs-right",
    debateId: "force-vs-right",
    displayReference: "Tucídides — História da Guerra do Peloponeso, Livro V",
    technicalReference:
      "GBWW Vol. 6 · Thucydides · History of the Peloponnesian War · BK V · ch. 84-116",
    gbwwVolume: 6,
    volumeTitle: "Volume 6 — Herodotus, Thucydides",
    volumePageUrl: "/volumes/6",
    volumePdfUrl: "",
    author: "Tucídides",
    work: "História da Guerra do Peloponeso",
    internalLocation: "Livro V, caps. 84–116",
    role: "Diálogo dos Mélios: 'Os fortes fazem o que podem; os fracos sofrem o que devem.' A versão histórica mais brutal do argumento que Trasímaco faz filosoficamente.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "guerra", "lei"],
  },

  // ── VINGANÇA VS. JULGAMENTO CÍVICO ─────────────────────────────────────────
  {
    id: "ref-justice-aeschylus-oresteia-eumenides",
    ideaSlug: "justica",
    topicId: "justice-vengeance-vs-civic-judgment",
    displayReference: "Ésquilo — Eumênides (Oresteia, Parte III)",
    technicalReference: "GBWW Vol. 5 · Aeschylus · Eumenides · localização em verificação",
    gbwwVolume: 5,
    volumeTitle: "Volume 5 — Aeschylus, Sophocles, Euripides, Aristophanes",
    volumePageUrl: "/volumes/5",
    volumePdfUrl: "",
    author: "Ésquilo",
    work: "Eumênides",
    internalLocation: "Peça completa",
    role: "Atena cria o primeiro tribunal ateniense para julgar Orestes. A lógica da vingança privada (Erínias) é substituída pelo julgamento público — origem da justiça cívica.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "punição", "lei"],
  },

  // ── LEI NÃO ESCRITA VS. LEI DO ESTADO ──────────────────────────────────────
  {
    id: "ref-justice-sophocles-antigone",
    ideaSlug: "justica",
    topicId: "justice-unwritten-law-vs-state-law",
    displayReference: "Sófocles — Antígona",
    technicalReference: "GBWW Vol. 5 · Sophocles · Antigone · localização em verificação",
    gbwwVolume: 5,
    volumeTitle: "Volume 5 — Aeschylus, Sophocles, Euripides, Aristophanes",
    volumePageUrl: "/volumes/5",
    volumePdfUrl: "",
    author: "Sófocles",
    work: "Antígona",
    internalLocation: "Peça completa",
    role: "Antígona desobedece a Creonte invocando leis não escritas e imortais dos deuses, superiores aos decretos humanos. Tensão clássica entre obrigação moral e lei civil.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "lei", "dever"],
  },

  // ── ALMA E CIDADE ───────────────────────────────────────────────────────────
  {
    id: "ref-justice-plato-republic-harmony",
    ideaSlug: "justica",
    topicId: "justice-soul-and-city",
    debateId: "arithmetic-vs-proportional-equality",
    displayReference: "Platão — A República, Livros II–IV",
    technicalReference: "GBWW Vol. 7 · Plato · Republic · BK II-IV · localização em verificação",
    gbwwVolume: 7,
    volumeTitle: "Volume 7 — Plato",
    volumePageUrl: "/volumes/7",
    volumePdfUrl: "",
    author: "Platão",
    work: "A República",
    internalLocation: "Livros II–IV",
    role: "Constrói a cidade ideal para ver a justiça 'em letras maiores'. Define justiça como cada parte (ou classe) cumprindo sua função própria — harmonia, não igualdade.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "virtude", "verdade"],
  },
  {
    id: "ref-justice-aristotle-politics-citizen",
    ideaSlug: "justica",
    topicId: "justice-soul-and-city",
    displayReference: "Aristóteles — Política, Livros I e III",
    technicalReference: "GBWW Vol. 9 · Aristotle · Politics · BK I, III · localização em verificação",
    gbwwVolume: 9,
    volumeTitle: "Volume 9 — Aristotle II",
    volumePageUrl: "/volumes/9",
    volumePdfUrl: "",
    author: "Aristóteles",
    work: "Política",
    internalLocation: "Livros I e III",
    role: "O ser humano é animal político por natureza. A cidade existe para o bem viver, não apenas para o sobreviver. A justiça política define quem são os cidadãos e como os cargos são distribuídos.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "igualdade", "lei"],
  },

  // ── DISTRIBUTIVA E CORRETIVA ────────────────────────────────────────────────
  {
    id: "ref-justice-aristotle-ethics-book-v",
    ideaSlug: "justica",
    topicId: "justice-distributive-corrective",
    debateId: "arithmetic-vs-proportional-equality",
    displayReference: "Aristóteles — Ética a Nicômaco, Livro V",
    technicalReference:
      "GBWW Vol. 9 · Aristotle · Nicomachean Ethics · BK V · localização em verificação",
    gbwwVolume: 9,
    volumeTitle: "Volume 9 — Aristotle II",
    volumePageUrl: "/volumes/9",
    volumePdfUrl: "",
    author: "Aristóteles",
    work: "Ética a Nicômaco",
    internalLocation: "Livro V",
    role: "Formula justiça distributiva (proporção geométrica: a cada um segundo seu mérito) e corretiva (proporção aritmética: restaurar o equilíbrio nas trocas). Definição mais influente da tradição.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "igualdade"],
  },

  // ── LEI NATURAL ─────────────────────────────────────────────────────────────
  {
    id: "ref-justice-augustine-city-of-god",
    ideaSlug: "justica",
    topicId: "justice-natural-law-positive-law",
    displayReference: "Agostinho — Cidade de Deus, Livros II e XIX",
    technicalReference:
      "GBWW Vol. 18 · Augustine · City of God · BK II, XIX · localização em verificação",
    gbwwVolume: 18,
    volumeTitle: "Volume 18 — Augustine",
    volumePageUrl: "/volumes/18",
    volumePdfUrl: "",
    author: "Agostinho de Hipona",
    work: "Cidade de Deus",
    internalLocation: "Livros II e XIX",
    role: "Sem justiça, o reino não passa de um grande bando de ladrões. A justiça terrena é limitada; a verdadeira justiça pertence à Cidade de Deus. Crítica ao Império Romano como exemplo de poder sem justiça.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "deus", "lei"],
  },
  {
    id: "ref-justice-aquinas-summa-law",
    ideaSlug: "justica",
    topicId: "justice-natural-law-positive-law",
    displayReference: "Tomás de Aquino — Suma Teológica, Tratado da Lei",
    technicalReference:
      "GBWW Vol. 19-20 · Aquinas · Summa Theologica · I-II, QQ. 90-97 · localização em verificação",
    gbwwVolume: 19,
    volumeTitle: "Volume 19 — Thomas Aquinas I",
    volumePageUrl: "/volumes/19",
    volumePdfUrl: "",
    author: "Tomás de Aquino",
    work: "Suma Teológica",
    internalLocation: "Parte I-II, Questões 90–97",
    role: "Define quatro tipos de lei: eterna, natural, humana e divina. A lei humana deve derivar da natural; uma lei injusta não é lei verdadeira. Síntese entre Aristóteles e o Cristianismo.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "lei", "deus"],
  },

  // ── CONTRATO SOCIAL ─────────────────────────────────────────────────────────
  {
    id: "ref-justice-hobbes-leviathan-covenant",
    ideaSlug: "justica",
    topicId: "justice-contract-sovereignty",
    debateId: "natural-vs-conventional-justice",
    displayReference: "Hobbes — Leviatã, Parte I, Capítulos 13–15",
    technicalReference:
      "GBWW Vol. 23 · Hobbes · Leviathan · Part I, ch. 13-15 · localização em verificação",
    gbwwVolume: 23,
    volumeTitle: "Volume 23 — Machiavelli, Hobbes",
    volumePageUrl: "/volumes/23",
    volumePdfUrl: "",
    author: "Thomas Hobbes",
    work: "Leviatã",
    internalLocation: "Parte I, Capítulos 13–15",
    role: "No estado de natureza, não há injustiça: 'onde não há lei comum, não há injustiça'. O pacto social cria o soberano; com ele nasce a possibilidade de justo e injusto.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "lei", "estado"],
  },
  {
    id: "ref-justice-locke-second-treatise",
    ideaSlug: "justica",
    topicId: "justice-contract-sovereignty",
    debateId: "natural-vs-conventional-justice",
    displayReference: "Locke — Segundo Tratado sobre o Governo Civil",
    technicalReference:
      "GBWW Vol. 35 · Locke · Second Treatise of Government · localização em verificação",
    gbwwVolume: 35,
    volumeTitle: "Volume 35 — Locke, Berkeley, Hume",
    volumePageUrl: "/volumes/35",
    volumePdfUrl: "",
    author: "John Locke",
    work: "Segundo Tratado sobre o Governo Civil",
    internalLocation: "Capítulos 2–9",
    role: "Há direitos naturais — vida, liberdade, propriedade — anteriores ao Estado. O governo existe para protegê-los, não para criá-los. Se os violar, o povo tem o direito de resistir.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "liberdade", "propriedade"],
  },

  // ── UTILIDADE ────────────────────────────────────────────────────────────────
  {
    id: "ref-justice-hume-enquiry-artificial-virtue",
    ideaSlug: "justica",
    topicId: "justice-utility-convention",
    debateId: "natural-vs-conventional-justice",
    displayReference: "Hume — Investigação sobre os Princípios da Moral, Seção III",
    technicalReference:
      "GBWW Vol. 35 · Hume · An Enquiry Concerning the Principles of Morals · Section III · localização em verificação",
    gbwwVolume: 35,
    volumeTitle: "Volume 35 — Locke, Berkeley, Hume",
    volumePageUrl: "/volumes/35",
    volumePdfUrl: "",
    author: "David Hume",
    work: "Investigação sobre os Princípios da Moral",
    internalLocation: "Seção III",
    role: "A justiça é uma virtude artificial: não é natural, mas inventada porque é útil. Sem escassez e sem egoísmo, não haveria necessidade de regras de propriedade. Sua única fundação é a utilidade.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "virtude", "propriedade"],
  },
  {
    id: "ref-justice-mill-utilitarianism",
    ideaSlug: "justica",
    topicId: "justice-utility-convention",
    debateId: "justice-vs-utility",
    displayReference: "Mill — Utilitarismo, Capítulo 5",
    technicalReference:
      "GBWW Vol. 43 · Mill · Utilitarianism · ch. 5 · localização em verificação",
    gbwwVolume: 43,
    volumeTitle: "Volume 43 — American State Papers, The Federalist, J. S. Mill",
    volumePageUrl: "/volumes/43",
    volumePdfUrl: "",
    author: "John Stuart Mill",
    work: "Utilitarismo",
    internalLocation: "Capítulo 5",
    role: "A justiça é a parte da moral que protege direitos essenciais ao bem-estar. O que torna a injustiça especialmente grave é a violação de um direito de alguém — e direitos são fundados na utilidade.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "liberdade", "felicidade"],
  },

  // ── KANT ──────────────────────────────────────────────────────────────────────
  {
    id: "ref-justice-kant-science-of-right",
    ideaSlug: "justica",
    topicId: "justice-liberty-universal-law",
    debateId: "liberty-and-justice",
    displayReference: "Kant — Metafísica dos Costumes: Ciência do Direito",
    technicalReference:
      "GBWW Vol. 42 · Kant · The Science of Right · localização em verificação",
    gbwwVolume: 42,
    volumeTitle: "Volume 42 — Kant",
    volumePageUrl: "/volumes/42",
    volumePdfUrl: "",
    author: "Immanuel Kant",
    work: "Metafísica dos Costumes (Ciência do Direito)",
    role: "Define o direito como o conjunto das condições sob as quais o arbítrio de um pode coexistir com o arbítrio de outro segundo uma lei universal de liberdade. Fórmula fundamental da justiça liberal.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "liberdade"],
  },
  {
    id: "ref-justice-kant-punishment-retribution",
    ideaSlug: "justica",
    topicId: "justice-punishment",
    displayReference: "Kant — Metafísica dos Costumes: Teoria do Direito, §49",
    technicalReference:
      "GBWW Vol. 42 · Kant · The Science of Right · §49 · localização em verificação",
    gbwwVolume: 42,
    volumeTitle: "Volume 42 — Kant",
    volumePageUrl: "/volumes/42",
    volumePdfUrl: "",
    author: "Immanuel Kant",
    work: "Metafísica dos Costumes (Ciência do Direito)",
    internalLocation: "§49",
    role: "A pena judicial nunca pode ser apenas um meio para outro fim. Deve ser imposta porque o criminoso cometeu o crime. Fundação do retributivismo: a justiça exige punir independente de consequências.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "punição"],
  },

  // ── MARX ──────────────────────────────────────────────────────────────────────
  {
    id: "ref-justice-marx-capital-surplus-value",
    ideaSlug: "justica",
    topicId: "justice-economic-class",
    debateId: "force-vs-right",
    displayReference: "Marx — O Capital, Livro I, Capítulos 6–7",
    technicalReference:
      "GBWW Vol. 50 · Marx · Capital · Vol. I, ch. 6-7 · localização em verificação",
    gbwwVolume: 50,
    volumeTitle: "Volume 50 — Marx, Engels",
    volumePageUrl: "/volumes/50",
    volumePdfUrl: "",
    author: "Karl Marx",
    work: "O Capital",
    internalLocation: "Livro I, Capítulos 6–7",
    role: "Analisa como a forma-salário parece justa (troca livre de equivalentes) mas esconde a extração de mais-valia. A exploração do trabalho é estrutural, não acidental — não pode ser corrigida por redistribuição.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "trabalho", "propriedade"],
  },
  {
    id: "ref-justice-marx-critique-gotha",
    ideaSlug: "justica",
    topicId: "justice-economic-class",
    displayReference: "Marx — Crítica ao Programa de Gotha",
    technicalReference:
      "GBWW Vol. 50 · Marx · Critique of the Gotha Programme · localização em verificação",
    gbwwVolume: 50,
    volumeTitle: "Volume 50 — Marx, Engels",
    volumePageUrl: "/volumes/50",
    volumePdfUrl: "",
    author: "Karl Marx",
    work: "Crítica ao Programa de Gotha",
    role: "Formula o princípio comunista: 'De cada um segundo sua capacidade, a cada um segundo sua necessidade.' Critica a 'igualdade' burguesa que aplica o mesmo critério a pessoas em situações desiguais.",
    relevance: "central",
    evidenceStatus: "em_verificacao",
    connectedIdeaIds: ["justica", "igualdade", "trabalho"],
  },
];

export function getReferencesByTopic(topicId: string): SyntopiconReference[] {
  return syntopiconReferences.filter((r) => r.topicId === topicId);
}

export function getReferencesByVolume(volumeNumber: number): SyntopiconReference[] {
  return syntopiconReferences.filter((r) => r.gbwwVolume === volumeNumber);
}

export function getReferencesByDebate(debateId: string): SyntopiconReference[] {
  return syntopiconReferences.filter((r) => r.debateId === debateId);
}

export function getJusticeReferences(): SyntopiconReference[] {
  return syntopiconReferences.filter((r) => r.ideaSlug === "justica");
}
